
{"action":"scan-qr","pass_type":"checkin","qr":"26@@6d7e0"}
{"action":"scan-qr","pass_type":"checkout","qr":"26@@6d7e0"}
{"action":"scan-qr","pass_type":"checkin","qr":"23@@498b0"}
{"action":"scan-qr","pass_type":"checkout","qr":"23@@498b0"}
{"action":"scan-qr","pass_type":"checkin","qr":"24@@6ec1c"}
{"action":"scan-qr","pass_type":"checkin","qr":"26@@6d7e0"}
{"action":"scan-qr","pass_type":"checkout","qr":"26@@6d7e0"}
{"action":"scan-qr","pass_type":"checkin","qr":"23@@498b0"}
{"action":"scan-qr","pass_type":"checkin","qr":"24@@6ec1c"}
{"action":"scan-qr","pass_type":"checkin","qr":"25@@59d46"}
{"action":"scan-qr","pass_type":"checkin","qr":"26@@6d7e0"}
{"action":"scan-qr","pass_type":"checkin","qr":"23@@498b0"}
{"action":"scan-qr","pass_type":"checkin","qr":"26@@6d7e0"}
{"action":"scan-qr","pass_type":"checkin","qr":"26@@6d7e0"}
{"action":"scan-qr","pass_type":"checkin","qr":"24@@6ec1c"}
{"action":"scan-qr","pass_type":"checkout","qr":"24@@6ec1c"}
{"action":"scan-qr","pass_type":"checkin","qr":"24@@6ec1c"}
{"action":"scan-qr","pass_type":"checkin","qr":"26@@6d7e0"}
{"action":"scan-qr","pass_type":"checkin","qr":"24@@6ec1c"}
{"action":"scan-qr","pass_type":"checkin","qr":"26@@6d7e0"}
{"action":"scan-qr","pass_type":"checkin","qr":"24@@6ec1c"}
{"action":"scan-qr","pass_type":"checkin","qr":"23@@498b0"}
{"action":"scan-qr","pass_type":"checkout","qr":"24@@6ec1c"}
{"action":"scan-qr","pass_type":"checkout","qr":"24@@6ec1c"}
{"action":"scan-qr","pass_type":"checkout","qr":"26@@6d7e0"}
{"action":"scan-qr","pass_type":"checkout","qr":"23@@498b0"}